kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  labels:
    app: ingress-nginx
data:
  proxy-body-size: "20M"
  proxy-read-timeout: "300"
  proxy-send-timeout: "300"
